var searchData=
[
  ['ianylinelistener',['IAnylineListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_anyline_listener.html',1,'Anyline::SDK::Core']]],
  ['ianylinescanresult',['IAnylineScanResult',['../interface_anyline_1_1_s_d_k_1_1_models_1_1_i_anyline_scan_result.html',1,'Anyline::SDK::Models']]],
  ['icameralistener',['ICameraListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_camera_listener.html',1,'Anyline::SDK::Camera']]],
  ['icapturemanager',['ICaptureManager',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_capture_manager.html',1,'Anyline::SDK::Camera']]],
  ['iconfigurablecharacterconfig',['IConfigurableCharacterConfig',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_configurable_character_config.html',1,'Anyline::SDK::Plugins']]],
  ['iconfigurablecharacterconfig_3c_20string_20_3e',['IConfigurableCharacterConfig&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_configurable_character_config.html',1,'Anyline::SDK::Plugins']]],
  ['id',['ID',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline.SDK.Plugins.ID.ID'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline.SDK.Plugins.ID.ID&lt; TFieldConfidences &gt;']]],
  ['id_3c_20drivinglicensefieldconfidences_20_3e',['ID&lt; DrivingLicenseFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['id_3c_20germanidfrontfieldconfidences_20_3e',['ID&lt; GermanIDFrontFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['id_3c_20mrzfieldconfidences_20_3e',['ID&lt; MrzFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idconfig',['IDConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html',1,'Anyline.SDK.Plugins.ID.IDConfig'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html#aa591eed19a9f53ed50dbf14d7090935e',1,'Anyline.SDK.Plugins.ID.IDConfig.IDConfig()'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html#abd845960caad3256e8e10a4eb153f9c2',1,'Anyline.SDK.Plugins.ID.IDConfig.IDConfig(JsonObject jsonObject)']]],
  ['idfieldconfidences',['IDFieldConfidences',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_field_confidences.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idfieldscanoptions',['IDFieldScanOptions',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_field_scan_options.html',1,'Anyline.SDK.Plugins.ID.IDFieldScanOptions'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html#aa13f1654252d28fde3fe74fb34eb2912',1,'Anyline.SDK.Plugins.ID.IDConfig.IDFieldScanOptions()']]],
  ['idminfieldconfidences',['IDMinFieldConfidences',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html#af7394264a77dfb723899044ad0fd67e3',1,'Anyline::SDK::Plugins::ID::IDConfig']]],
  ['idrivinglicenseidentificationfields',['IDrivingLicenseIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20fieldscanoption_20_3e',['IDrivingLicenseIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20int_20_3e',['IDrivingLicenseIdentificationFields&lt; int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20string_20_3e',['IDrivingLicenseIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanplugin',['IDScanPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanviewplugin',['IDScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_view_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iexceptionlistener',['IExceptionListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_i_exception_listener.html',1,'Anyline::SDK::Core::Exceptions']]],
  ['igermanidfrontidentificationfields',['IGermanIDFrontIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20fieldscanoption_20_3e',['IGermanIDFrontIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20int_20_3e',['IGermanIDFrontIdentificationFields&lt; int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20string_20_3e',['IGermanIDFrontIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iidentificationfields',['IIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iimageprovider',['IImageProvider',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_image_provider.html',1,'Anyline::SDK::Core']]],
  ['image',['Image',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_meter.html#abdaf720c805b3d2fd500a6a37020b2c3abe53a0541a6d36f6ecb879fa2c584b08',1,'Anyline::SDK::Plugins::Meter']]],
  ['imei',['IMEI',['../struct_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_regex.html#adf3d9fd359aca9935c8372bd12ba5e2e',1,'Anyline::SDK::Plugins::Ocr::AnylineOcrRegex']]],
  ['imrzidentificationfields',['IMrzIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentificationFields&lt; T &gt;'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentificationFields&lt; T, V &gt;']]],
  ['imrzidentificationfields_3c_20fieldscanoption_20_3e',['IMrzIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20int_2c_20int_20_3e',['IMrzIdentificationFields&lt; int, int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20string_20_3e',['IMrzIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20t_2c_20bool_20_3e',['IMrzIdentificationFields&lt; T, bool &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['info',['Info',['../namespace_anyline_1_1_s_d_k_1_1_util.html#a44753ef31f217f72f7825f856ba71715a4059b0251f66a18cb56f544728796875',1,'Anyline::SDK::Util']]],
  ['init',['Init',['../class_anyline_1_1_s_d_k_1_1_views_1_1_scan_view.html#add272f42830425cb1c0e5dd7e7e19621',1,'Anyline.SDK.Views.ScanView.Init(JsonObject jsonObject, string licenseKey)'],['../class_anyline_1_1_s_d_k_1_1_views_1_1_scan_view.html#a1ca1ea3c7d5a15cff492431c312269a3',1,'Anyline.SDK.Views.ScanView.Init(string jsonAssetPath, string licenseKey)']]],
  ['iphotocapturelistener',['IPhotoCaptureListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_meter_1_1_i_photo_capture_listener.html',1,'Anyline::SDK::Plugins::Meter']]],
  ['isbn',['ISBN',['../struct_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_regex.html#a8800d12c27fb2fc83079575fa649cc02',1,'Anyline::SDK::Plugins::Ocr::AnylineOcrRegex']]],
  ['isbrighttextondark',['IsBrightTextOnDark',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#a5f26f4886daf7ac7d5d8d54769d9d8a6',1,'Anyline::SDK::Plugins::Ocr::AnylineOcrConfig']]],
  ['iscameraopen',['IsCameraOpen',['../class_anyline_1_1_s_d_k_1_1_camera_1_1_camera_view.html#adbdde05e978642206b470efdb65f02ce',1,'Anyline::SDK::Camera::CameraView']]],
  ['iscaninfolistener',['IScanInfoListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_info_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin',['IScanPlugin',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin_3c_20tscanresult_20_3e',['IScanPlugin&lt; TScanResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanresultlistener',['IScanResultListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener&lt; T &gt;']]],
  ['iscanrunskippedlistener',['IScanRunSkippedListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_run_skipped_listener.html',1,'Anyline::SDK::Plugins']]]
];
