var searchData=
[
  ['ianylinelistener',['IAnylineListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_anyline_listener.html',1,'Anyline::SDK::Core']]],
  ['ianylinemoduleresultlistener',['IAnylineModuleResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline.SDK.Modules.IAnylineModuleResultListener'],['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline.SDK.Modules.IAnylineModuleResultListener&lt; AnylineScanResult &gt;']]],
  ['ianylinemoduleresultlistener_3c_20anylineocrresult_20_3e',['IAnylineModuleResultListener&lt; AnylineOcrResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20barcoderesult_20_3e',['IAnylineModuleResultListener&lt; BarcodeResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20energyresult_20_3e',['IAnylineModuleResultListener&lt; EnergyResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20licenseplateresult_20_3e',['IAnylineModuleResultListener&lt; LicensePlateResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20mrzresult_20_3e',['IAnylineModuleResultListener&lt; MrzResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleview',['IAnylineModuleView',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleview_3c_20tmoduleresultlistenertype_20_3e',['IAnylineModuleView&lt; TModuleResultListenerType &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html',1,'Anyline::SDK::Modules']]],
  ['ianylineocrresultlistener',['IAnylineOcrResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_ocr_1_1_i_anyline_ocr_result_listener.html',1,'Anyline::SDK::Modules::Ocr']]],
  ['ianylinescanresult',['IAnylineScanResult',['../interface_anyline_1_1_s_d_k_1_1_models_1_1_i_anyline_scan_result.html',1,'Anyline::SDK::Models']]],
  ['ibarcoderesultlistener',['IBarcodeResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_barcode_1_1_i_barcode_result_listener.html',1,'Anyline::SDK::Modules::Barcode']]],
  ['icameralistener',['ICameraListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_camera_listener.html',1,'Anyline::SDK::Camera']]],
  ['icombinedimageprovider',['ICombinedImageProvider',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_combined_image_provider.html',1,'Anyline::SDK::Camera']]],
  ['id',['ID',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idconfig',['IDConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html',1,'Anyline::SDK::Plugins::ID']]],
  ['identification',['Identification',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_mrz_1_1_identification.html',1,'Anyline::SDK::Modules::Mrz']]],
  ['idfieldscanoptions',['IDFieldScanOptions',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_field_scan_options.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentification',['IDrivingLicenseIdentification',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentification_3c_20fieldscanoption_20_3e',['IDrivingLicenseIdentification&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentification_3c_20string_20_3e',['IDrivingLicenseIdentification&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanplugin',['IDScanPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanviewplugin',['IDScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_view_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['ienergyresultlistener',['IEnergyResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_energy_1_1_i_energy_result_listener.html',1,'Anyline::SDK::Modules::Energy']]],
  ['iexceptionlistener',['IExceptionListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_i_exception_listener.html',1,'Anyline::SDK::Core::Exceptions']]],
  ['igermanidfrontidentification',['IGermanIDFrontIdentification',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentification_3c_20fieldscanoption_20_3e',['IGermanIDFrontIdentification&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentification_3c_20string_20_3e',['IGermanIDFrontIdentification&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['ihighresolutionimagelistener',['IHighResolutionImageListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_high_resolution_image_listener.html',1,'Anyline::SDK::Camera']]],
  ['ihighresolutionimageprovider',['IHighResolutionImageProvider',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_high_resolution_image_provider.html',1,'Anyline::SDK::Camera']]],
  ['iidentification',['IIdentification',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iimageprovider',['IImageProvider',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_image_provider.html',1,'Anyline::SDK::Core']]],
  ['ilicenseplateresultlistener',['ILicensePlateResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_license_plate_1_1_i_license_plate_result_listener.html',1,'Anyline::SDK::Modules::LicensePlate']]],
  ['image',['Image',['../namespace_anyline_1_1_s_d_k_1_1_modules_1_1_energy.html#a6f66509040a9c08394c80fbb74a63087abe53a0541a6d36f6ecb879fa2c584b08',1,'Anyline::SDK::Modules::Energy']]],
  ['imei',['IMEI',['../struct_anyline_1_1_s_d_k_1_1_modules_1_1_ocr_1_1_anyline_ocr_regex.html#a758c3188ebd5c7252c8bc205ca4e0247',1,'Anyline::SDK::Modules::Ocr::AnylineOcrRegex']]],
  ['imrzidentification',['IMrzIdentification',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentification&lt; T &gt;'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentification&lt; T, V &gt;']]],
  ['imrzidentification_3c_20fieldscanoption_20_3e',['IMrzIdentification&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentification_3c_20string_20_3e',['IMrzIdentification&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentification_3c_20t_2c_20bool_20_3e',['IMrzIdentification&lt; T, bool &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzresultlistener',['IMrzResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_mrz_1_1_i_mrz_result_listener.html',1,'Anyline::SDK::Modules::Mrz']]],
  ['info',['Info',['../namespace_anyline_1_1_s_d_k_1_1_util.html#a44753ef31f217f72f7825f856ba71715a4059b0251f66a18cb56f544728796875',1,'Anyline::SDK::Util']]],
  ['init',['Init',['../class_anyline_1_1_s_d_k_1_1_views_1_1_scan_view.html#add272f42830425cb1c0e5dd7e7e19621',1,'Anyline.SDK.Views.ScanView.Init(JsonObject jsonObject, string licenseKey)'],['../class_anyline_1_1_s_d_k_1_1_views_1_1_scan_view.html#a1ca1ea3c7d5a15cff492431c312269a3',1,'Anyline.SDK.Views.ScanView.Init(string jsonAssetPath, string licenseKey)']]],
  ['initanyline',['InitAnyline',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_anyline_module_view.html#a6e4cf366c15fa2f6517dd9c8bf1a7957',1,'Anyline.SDK.Modules.AnylineModuleView.InitAnyline()'],['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html#a3186da39aa6d2ed70c0ef08a949064fc',1,'Anyline.SDK.Modules.IAnylineModuleView.InitAnyline()']]],
  ['invokescanviewupdate',['InvokeScanViewUpdate',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_anyline_module_view.html#a441d5ea4502011fdecb54d389001d4a2',1,'Anyline::SDK::Modules::AnylineModuleView']]],
  ['iphotocapturelistener',['IPhotoCaptureListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_energy_1_1_i_photo_capture_listener.html',1,'Anyline::SDK::Modules::Energy']]],
  ['isbn',['ISBN',['../struct_anyline_1_1_s_d_k_1_1_modules_1_1_ocr_1_1_anyline_ocr_regex.html#af19e490c042becc59be1f00ba8f9f26f',1,'Anyline::SDK::Modules::Ocr::AnylineOcrRegex']]],
  ['isbrighttextondark',['IsBrightTextOnDark',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_ocr_1_1_anyline_ocr_config.html#af5b7d9d685db74c3f5f1cfe1bbff48c8',1,'Anyline::SDK::Modules::Ocr::AnylineOcrConfig']]],
  ['iscameraopen',['IsCameraOpen',['../class_anyline_1_1_s_d_k_1_1_camera_1_1_camera_view.html#adbdde05e978642206b470efdb65f02ce',1,'Anyline.SDK.Camera.CameraView.IsCameraOpen()'],['../class_anyline_1_1_s_d_k_1_1_modules_1_1_anyline_module_view.html#a2fb4e2ec6f16ee0624f39d3a9bb54371',1,'Anyline.SDK.Modules.AnylineModuleView.IsCameraOpen()']]],
  ['iscaninfolistener',['IScanInfoListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_info_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin',['IScanPlugin',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline.SDK.Plugins.IScanPlugin'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline.SDK.Plugins.IScanPlugin&lt; TScanPluginResultType &gt;']]],
  ['iscanplugin_3c_20tscanpluginresulttype_20_3e',['IScanPlugin&lt; TScanPluginResultType &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin_3c_20tscanresult_20_3e',['IScanPlugin&lt; TScanResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanresultlistener',['IScanResultListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener&lt; T &gt;']]],
  ['iscanresultlistener_3c_20tpluginscanresulttype_20_3e',['IScanResultListener&lt; TPluginScanResultType &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanrunskippedlistener',['IScanRunSkippedListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_run_skipped_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanview',['IScanView',['../interface_anyline_1_1_s_d_k_1_1_views_1_1_i_scan_view.html',1,'Anyline::SDK::Views']]],
  ['iscanviewplugin',['IScanViewPlugin',['../interface_anyline_1_1_s_d_k_1_1_views_1_1_i_scan_view_plugin.html',1,'Anyline::SDK::Views']]],
  ['isscanning',['IsScanning',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_anyline_module_view.html#a6407158d47eddb94df2b4e367286b324',1,'Anyline.SDK.Modules.AnylineModuleView.IsScanning()'],['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html#ae2197e40f27f03147bdc5c6a01720519',1,'Anyline.SDK.Modules.IAnylineModuleView.IsScanning()']]]
];
