var searchData=
[
  ['abstractbasescanviewplugin',['AbstractBaseScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_base_scan_view_plugin.html',1,'Anyline::SDK::ViewPlugins']]],
  ['abstractscanplugin',['AbstractScanPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_abstract_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['abstractscanplugin_3c_20barcodescanresult_20_3e',['AbstractScanPlugin&lt; BarcodeScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_abstract_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['abstractscanplugin_3c_20licenseplatescanresult_20_3e',['AbstractScanPlugin&lt; LicensePlateScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_abstract_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['abstractscanplugin_3c_20meterscanresult_20_3e',['AbstractScanPlugin&lt; MeterScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_abstract_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['abstractscanplugin_3c_20ocrscanresult_20_3e',['AbstractScanPlugin&lt; OcrScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_abstract_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['abstractscanviewplugin',['AbstractScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline.SDK.ViewPlugins.AbstractScanViewPlugin'],['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline.SDK.ViewPlugins.AbstractScanViewPlugin&lt; TScanPlugin, TScanResult &gt;']]],
  ['abstractscanviewplugin_3c_20barcodescanplugin_2c_20barcodescanresult_20_3e',['AbstractScanViewPlugin&lt; BarcodeScanPlugin, BarcodeScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline::SDK::ViewPlugins']]],
  ['abstractscanviewplugin_3c_20licenseplatescanplugin_2c_20licenseplatescanresult_20_3e',['AbstractScanViewPlugin&lt; LicensePlateScanPlugin, LicensePlateScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline::SDK::ViewPlugins']]],
  ['abstractscanviewplugin_3c_20meterscanplugin_2c_20meterscanresult_20_3e',['AbstractScanViewPlugin&lt; MeterScanPlugin, MeterScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline::SDK::ViewPlugins']]],
  ['abstractscanviewplugin_3c_20ocrscanplugin_2c_20ocrscanresult_20_3e',['AbstractScanViewPlugin&lt; OcrScanPlugin, OcrScanResult &gt;',['../class_anyline_1_1_s_d_k_1_1_view_plugins_1_1_abstract_scan_view_plugin.html',1,'Anyline::SDK::ViewPlugins']]],
  ['abstractscanviewplugincomposite',['AbstractScanViewPluginComposite',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_composites_1_1_abstract_scan_view_plugin_composite.html',1,'Anyline::SDK::Plugins::Composites']]],
  ['aftereverycaptureframe',['AfterEveryCaptureFrame',['../namespace_anyline_1_1_s_d_k_1_1_util.html#ac1aae387015883581404690b7ce329d1a34860bd70c9b5384800b4a9898763c91',1,'Anyline::SDK::Util']]],
  ['aftereveryprocessedimage',['AfterEveryProcessedImage',['../namespace_anyline_1_1_s_d_k_1_1_util.html#ac1aae387015883581404690b7ce329d1a0e7d5a4199f9ca6ccf8f90579c1e7f71',1,'Anyline::SDK::Util']]],
  ['allowlowercase',['AllowLowerCase',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#a019c3fe822dcd19c8514b55d98eec418',1,'Anyline::SDK::Plugins::Ocr::AnylineOcrConfig']]],
  ['always',['Always',['../namespace_anyline_1_1_s_d_k_1_1_util.html#ac1aae387015883581404690b7ce329d1a68eec46437c384d8dad18d5464ebc35c',1,'Anyline::SDK::Util']]],
  ['anyline',['Anyline',['../namespace_anyline.html',1,'']]],
  ['anylinebaseconfig',['AnylineBaseConfig',['../class_anyline_1_1_s_d_k_1_1_views_1_1_anyline_base_config.html',1,'Anyline::SDK::Views']]],
  ['anylineexception',['AnylineException',['../class_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_anyline_exception.html',1,'Anyline.SDK.Core.Exceptions.AnylineException'],['../class_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_anyline_exception.html#a2f2ed94a25bf8627e3ef8cda11f83902',1,'Anyline.SDK.Core.Exceptions.AnylineException.AnylineException()']]],
  ['anylineimage',['AnylineImage',['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_image.html',1,'Anyline.SDK.Models.AnylineImage'],['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_image.html#a2589309b9cfadcacc81f9f4922194541',1,'Anyline.SDK.Models.AnylineImage.AnylineImage(byte[] buffer, int width, int height)'],['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_image.html#aac8fc8e8e3d6129f5fa6871cc1cb4e39',1,'Anyline.SDK.Models.AnylineImage.AnylineImage(WriteableBitmap bitmap)']]],
  ['anylineimageprovider',['AnylineImageProvider',['../class_anyline_1_1_s_d_k_1_1_camera_1_1_anyline_image_provider.html',1,'Anyline::SDK::Camera']]],
  ['anylineocrbaseconfig',['AnylineOcrBaseConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_base_config.html',1,'Anyline::SDK::Plugins::Ocr']]],
  ['anylineocrconfig',['AnylineOcrConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrConfig'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#a04a005a3a07f7450feb0addb729ecbea',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrConfig.AnylineOcrConfig()'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#a169b99ef3106ed9136f1330c90db4d19',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrConfig.AnylineOcrConfig(string fileName)'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#a914295cbf0eea99925e0b3aa8b04671e',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrConfig.AnylineOcrConfig(JsonObject jsonObject)']]],
  ['anylineocrlanguage',['AnylineOcrLanguage',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_language.html',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrLanguage'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_language.html#a5ae996fff18d7f544067c61ab26ebeef',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrLanguage.AnylineOcrLanguage()']]],
  ['anylineocrregex',['AnylineOcrRegex',['../struct_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_regex.html',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrRegex'],['../struct_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_regex.html#a2785f3ac1d6274375a368749b30373f9',1,'Anyline.SDK.Plugins.Ocr.AnylineOcrRegex.AnylineOcrRegex()']]],
  ['anylinescanresult',['AnylineScanResult',['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_scan_result.html',1,'Anyline.SDK.Models.AnylineScanResult&lt; T &gt;'],['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_scan_result.html#a685b03519f5a49fefd19c9b3b9392e2b',1,'Anyline.SDK.Models.AnylineScanResult.AnylineScanResult()']]],
  ['anylinescanresult_3c_20tscanresulttype_20_3e',['AnylineScanResult&lt; TScanResultType &gt;',['../class_anyline_1_1_s_d_k_1_1_models_1_1_anyline_scan_result.html',1,'Anyline::SDK::Models']]],
  ['anylinesdk',['AnylineSDK',['../namespace_anyline_s_d_k.html',1,'']]],
  ['arealllanguagesanyfiles',['AreAllLanguagesAnyFiles',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr_1_1_anyline_ocr_config.html#aee35756f18b17d5ad966ca0a1eff6391',1,'Anyline::SDK::Plugins::Ocr::AnylineOcrConfig']]],
  ['argumentexception',['ArgumentException',['../class_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_argument_exception.html',1,'Anyline.SDK.Core.Exceptions.ArgumentException'],['../class_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_argument_exception.html#acf1c17f1d9ece20e9f1524858b13de0f',1,'Anyline.SDK.Core.Exceptions.ArgumentException.ArgumentException()']]],
  ['asset',['Asset',['../namespace_anyline_1_1_s_d_k_1_1_asset.html',1,'Anyline::SDK']]],
  ['autofocusinterval',['AutoFocusInterval',['../class_anyline_1_1_s_d_k_1_1_camera_1_1_focus_controller.html#a88181b2f1336a030370cdb4a2521c94d',1,'Anyline::SDK::Camera::FocusController']]],
  ['barcode',['Barcode',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_barcode.html',1,'Anyline::SDK::Plugins']]],
  ['camera',['Camera',['../namespace_anyline_1_1_s_d_k_1_1_camera.html',1,'Anyline::SDK']]],
  ['composites',['Composites',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_composites.html',1,'Anyline::SDK::Plugins']]],
  ['core',['Core',['../namespace_anyline_1_1_s_d_k_1_1_core.html',1,'Anyline::SDK']]],
  ['exceptions',['Exceptions',['../namespace_anyline_1_1_s_d_k_1_1_core_1_1_exceptions.html',1,'Anyline::SDK::Core']]],
  ['id',['ID',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d.html',1,'Anyline::SDK::Plugins']]],
  ['licenseplate',['LicensePlate',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_license_plate.html',1,'Anyline::SDK::Plugins']]],
  ['meter',['Meter',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_meter.html',1,'Anyline::SDK::Plugins']]],
  ['models',['Models',['../namespace_anyline_1_1_s_d_k_1_1_models.html',1,'Anyline::SDK']]],
  ['ocr',['Ocr',['../namespace_anyline_1_1_s_d_k_1_1_plugins_1_1_ocr.html',1,'Anyline::SDK::Plugins']]],
  ['panasonic',['Panasonic',['../namespace_anyline_1_1_s_d_k_1_1_camera_1_1_panasonic.html',1,'Anyline::SDK::Camera']]],
  ['plugins',['Plugins',['../namespace_anyline_1_1_s_d_k_1_1_plugins.html',1,'Anyline.SDK.Plugins'],['../namespace_anyline_s_d_k_1_1_s_d_k_1_1_plugins.html',1,'AnylineSDK.SDK.Plugins']]],
  ['reporting',['Reporting',['../namespace_anyline_1_1_s_d_k_1_1_reporting.html',1,'Anyline::SDK']]],
  ['sdk',['SDK',['../namespace_anyline_1_1_s_d_k.html',1,'Anyline.SDK'],['../namespace_anyline_s_d_k_1_1_s_d_k.html',1,'AnylineSDK.SDK']]],
  ['util',['Util',['../namespace_anyline_1_1_s_d_k_1_1_util.html',1,'Anyline::SDK']]],
  ['viewplugins',['ViewPlugins',['../namespace_anyline_1_1_s_d_k_1_1_view_plugins.html',1,'Anyline::SDK']]],
  ['views',['Views',['../namespace_anyline_1_1_s_d_k_1_1_views.html',1,'Anyline::SDK']]]
];
