var searchData=
[
  ['ianylinelistener',['IAnylineListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_anyline_listener.html',1,'Anyline::SDK::Core']]],
  ['ianylinemoduleresultlistener',['IAnylineModuleResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline.SDK.Modules.IAnylineModuleResultListener'],['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline.SDK.Modules.IAnylineModuleResultListener&lt; AnylineScanResult &gt;']]],
  ['ianylinemoduleresultlistener_3c_20anylineocrresult_20_3e',['IAnylineModuleResultListener&lt; AnylineOcrResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20barcoderesult_20_3e',['IAnylineModuleResultListener&lt; BarcodeResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20energyresult_20_3e',['IAnylineModuleResultListener&lt; EnergyResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20licenseplateresult_20_3e',['IAnylineModuleResultListener&lt; LicensePlateResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleresultlistener_3c_20mrzresult_20_3e',['IAnylineModuleResultListener&lt; MrzResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_result_listener.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleview',['IAnylineModuleView',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html',1,'Anyline::SDK::Modules']]],
  ['ianylinemoduleview_3c_20tmoduleresultlistenertype_20_3e',['IAnylineModuleView&lt; TModuleResultListenerType &gt;',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_i_anyline_module_view.html',1,'Anyline::SDK::Modules']]],
  ['ianylineocrresultlistener',['IAnylineOcrResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_ocr_1_1_i_anyline_ocr_result_listener.html',1,'Anyline::SDK::Modules::Ocr']]],
  ['ianylinescanresult',['IAnylineScanResult',['../interface_anyline_1_1_s_d_k_1_1_models_1_1_i_anyline_scan_result.html',1,'Anyline::SDK::Models']]],
  ['ibarcoderesultlistener',['IBarcodeResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_barcode_1_1_i_barcode_result_listener.html',1,'Anyline::SDK::Modules::Barcode']]],
  ['icameralistener',['ICameraListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_camera_listener.html',1,'Anyline::SDK::Camera']]],
  ['icombinedimageprovider',['ICombinedImageProvider',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_combined_image_provider.html',1,'Anyline::SDK::Camera']]],
  ['id',['ID',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idconfig',['IDConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html',1,'Anyline::SDK::Plugins::ID']]],
  ['identification',['Identification',['../class_anyline_1_1_s_d_k_1_1_modules_1_1_mrz_1_1_identification.html',1,'Anyline::SDK::Modules::Mrz']]],
  ['idscanplugin',['IDScanPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanviewplugin',['IDScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_view_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['ienergyresultlistener',['IEnergyResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_energy_1_1_i_energy_result_listener.html',1,'Anyline::SDK::Modules::Energy']]],
  ['iexceptionlistener',['IExceptionListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_i_exception_listener.html',1,'Anyline::SDK::Core::Exceptions']]],
  ['ihighresolutionimagelistener',['IHighResolutionImageListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_high_resolution_image_listener.html',1,'Anyline::SDK::Camera']]],
  ['ihighresolutionimageprovider',['IHighResolutionImageProvider',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_high_resolution_image_provider.html',1,'Anyline::SDK::Camera']]],
  ['iimageprovider',['IImageProvider',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_image_provider.html',1,'Anyline::SDK::Core']]],
  ['ilicenseplateresultlistener',['ILicensePlateResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_license_plate_1_1_i_license_plate_result_listener.html',1,'Anyline::SDK::Modules::LicensePlate']]],
  ['imrzresultlistener',['IMrzResultListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_mrz_1_1_i_mrz_result_listener.html',1,'Anyline::SDK::Modules::Mrz']]],
  ['iphotocapturelistener',['IPhotoCaptureListener',['../interface_anyline_1_1_s_d_k_1_1_modules_1_1_energy_1_1_i_photo_capture_listener.html',1,'Anyline::SDK::Modules::Energy']]],
  ['iscaninfolistener',['IScanInfoListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_info_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin',['IScanPlugin',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline.SDK.Plugins.IScanPlugin&lt; TScanPluginResultType &gt;'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline.SDK.Plugins.IScanPlugin']]],
  ['iscanplugin_3c_20tscanpluginresulttype_20_3e',['IScanPlugin&lt; TScanPluginResultType &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanresultlistener',['IScanResultListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener&lt; T &gt;']]],
  ['iscanresultlistener_3c_20tpluginscanresulttype_20_3e',['IScanResultListener&lt; TPluginScanResultType &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanrunskippedlistener',['IScanRunSkippedListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_run_skipped_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanview',['IScanView',['../interface_anyline_1_1_s_d_k_1_1_views_1_1_i_scan_view.html',1,'Anyline::SDK::Views']]],
  ['iscanviewplugin',['IScanViewPlugin',['../interface_anyline_1_1_s_d_k_1_1_views_1_1_i_scan_view_plugin.html',1,'Anyline::SDK::Views']]]
];
