var searchData=
[
  ['ianylinelistener',['IAnylineListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_anyline_listener.html',1,'Anyline::SDK::Core']]],
  ['ianylinescanresult',['IAnylineScanResult',['../interface_anyline_1_1_s_d_k_1_1_models_1_1_i_anyline_scan_result.html',1,'Anyline::SDK::Models']]],
  ['icameralistener',['ICameraListener',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_camera_listener.html',1,'Anyline::SDK::Camera']]],
  ['icapturemanager',['ICaptureManager',['../interface_anyline_1_1_s_d_k_1_1_camera_1_1_i_capture_manager.html',1,'Anyline::SDK::Camera']]],
  ['iconfigurablecharacterconfig',['IConfigurableCharacterConfig',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_configurable_character_config.html',1,'Anyline::SDK::Plugins']]],
  ['iconfigurablecharacterconfig_3c_20string_20_3e',['IConfigurableCharacterConfig&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_configurable_character_config.html',1,'Anyline::SDK::Plugins']]],
  ['id',['ID',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline.SDK.Plugins.ID.ID'],['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline.SDK.Plugins.ID.ID&lt; TFieldConfidences &gt;']]],
  ['id_3c_20drivinglicensefieldconfidences_20_3e',['ID&lt; DrivingLicenseFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['id_3c_20germanidfrontfieldconfidences_20_3e',['ID&lt; GermanIDFrontFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['id_3c_20mrzfieldconfidences_20_3e',['ID&lt; MrzFieldConfidences &gt;',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idconfig',['IDConfig',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_config.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idfieldconfidences',['IDFieldConfidences',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_field_confidences.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idfieldscanoptions',['IDFieldScanOptions',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_field_scan_options.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields',['IDrivingLicenseIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20fieldscanoption_20_3e',['IDrivingLicenseIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20int_20_3e',['IDrivingLicenseIdentificationFields&lt; int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idrivinglicenseidentificationfields_3c_20string_20_3e',['IDrivingLicenseIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_driving_license_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanplugin',['IDScanPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['idscanviewplugin',['IDScanViewPlugin',['../class_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_d_scan_view_plugin.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iexceptionlistener',['IExceptionListener',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_exceptions_1_1_i_exception_listener.html',1,'Anyline::SDK::Core::Exceptions']]],
  ['igermanidfrontidentificationfields',['IGermanIDFrontIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20fieldscanoption_20_3e',['IGermanIDFrontIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20int_20_3e',['IGermanIDFrontIdentificationFields&lt; int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['igermanidfrontidentificationfields_3c_20string_20_3e',['IGermanIDFrontIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_german_i_d_front_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iidentificationfields',['IIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iimageprovider',['IImageProvider',['../interface_anyline_1_1_s_d_k_1_1_core_1_1_i_image_provider.html',1,'Anyline::SDK::Core']]],
  ['imrzidentificationfields',['IMrzIdentificationFields',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentificationFields&lt; T &gt;'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline.SDK.Plugins.ID.IMrzIdentificationFields&lt; T, V &gt;']]],
  ['imrzidentificationfields_3c_20fieldscanoption_20_3e',['IMrzIdentificationFields&lt; FieldScanOption &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20int_2c_20int_20_3e',['IMrzIdentificationFields&lt; int, int &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20string_20_3e',['IMrzIdentificationFields&lt; string &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['imrzidentificationfields_3c_20t_2c_20bool_20_3e',['IMrzIdentificationFields&lt; T, bool &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_d_1_1_i_mrz_identification_fields.html',1,'Anyline::SDK::Plugins::ID']]],
  ['iphotocapturelistener',['IPhotoCaptureListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_meter_1_1_i_photo_capture_listener.html',1,'Anyline::SDK::Plugins::Meter']]],
  ['iscaninfolistener',['IScanInfoListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_info_listener.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin',['IScanPlugin',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanplugin_3c_20tscanresult_20_3e',['IScanPlugin&lt; TScanResult &gt;',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_plugin.html',1,'Anyline::SDK::Plugins']]],
  ['iscanresultlistener',['IScanResultListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener'],['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_result_listener.html',1,'Anyline.SDK.Plugins.IScanResultListener&lt; T &gt;']]],
  ['iscanrunskippedlistener',['IScanRunSkippedListener',['../interface_anyline_1_1_s_d_k_1_1_plugins_1_1_i_scan_run_skipped_listener.html',1,'Anyline::SDK::Plugins']]]
];
